FROM golang:1.16-alpine AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY *.go .

RUN go build -o /server

FROM alpine:latest

WORKDIR /

COPY --from=builder /server /server

COPY config.yaml .
COPY public ./public
COPY tmpl ./tmpl

EXPOSE 8080

CMD [ "/server" ]